# Spring Boot configuration
spring:
  datasource:
    url: jdbc:postgresql://3.12.85.162:5432/wist
    username: scott
    password: scott
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: create # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
# Logger configuration
#logging:
#  pattern:
#    console: "%d %-5level %logger : %msg%n"
#  level:
#    org.springframework: info
#    org.hibernate: debug
# Server configuration
server:
  port: 7777 #set your port
